package com.wen.bangumi.greenDAO;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "BANGUMI_ITEM".
 */
@Entity
public class BangumiItem {

    @Id
    private Long id;
    private int bangumi_id;
    private String name_cn;
    private Integer air_weekday;
    private String large_image;

    @Generated
    public BangumiItem() {
    }

    public BangumiItem(Long id) {
        this.id = id;
    }

    @Generated
    public BangumiItem(Long id, int bangumi_id, String name_cn, Integer air_weekday, String large_image) {
        this.id = id;
        this.bangumi_id = bangumi_id;
        this.name_cn = name_cn;
        this.air_weekday = air_weekday;
        this.large_image = large_image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getBangumi_id() {
        return bangumi_id;
    }

    public void setBangumi_id(int bangumi_id) {
        this.bangumi_id = bangumi_id;
    }

    public String getName_cn() {
        return name_cn;
    }

    public void setName_cn(String name_cn) {
        this.name_cn = name_cn;
    }

    public Integer getAir_weekday() {
        return air_weekday;
    }

    public void setAir_weekday(Integer air_weekday) {
        this.air_weekday = air_weekday;
    }

    public String getLarge_image() {
        return large_image;
    }

    public void setLarge_image(String large_image) {
        this.large_image = large_image;
    }

}
