package com.wen.bangumi.greenDAO;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bangumiItemDaoConfig;

    private final BangumiItemDao bangumiItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bangumiItemDaoConfig = daoConfigMap.get(BangumiItemDao.class).clone();
        bangumiItemDaoConfig.initIdentityScope(type);

        bangumiItemDao = new BangumiItemDao(bangumiItemDaoConfig, this);

        registerDao(BangumiItem.class, bangumiItemDao);
    }
    
    public void clear() {
        bangumiItemDaoConfig.clearIdentityScope();
    }

    public BangumiItemDao getBangumiItemDao() {
        return bangumiItemDao;
    }

}
